#!/usr/bin/env bash
# @file bundle.sh
# @brief Flatten the selected modules into one self-contained file
# @description
#   Produces `dybatpho.bundle.sh`: the bootstrap plus the chosen modules in one
#   file, with no `src/` directory beside it and nothing to source at run time.
#   That is what vendoring into another repository or baking into a container
#   image needs — one file to copy, one file to review, one file to check into
#   the consumer's tree.
#
#   The module set is resolved by `init.sh` itself: the script runs the real
#   bootstrap with the requested `--modules` and bundles exactly what it loaded,
#   in load order. Dependency resolution therefore cannot drift from the
#   library, and `--modules` means here what it means everywhere else, including
#   `all`.
#
#   Inside the bundle, `dybatpho::load` has nothing left to source, so it
#   succeeds for a bundled module and fails with a regeneration hint for
#   anything else. `dybatpho::module_list all` reports what the bundle carries
#   rather than what the library has, which is also what `dybatpho::doctor --all`
#   then checks.
#
#   The bundle is generated code: change the library and regenerate, never edit
#   the output.
#
# @example
#   scripts/bundle.sh                                   # core modules
#   scripts/bundle.sh --modules "logging git semver"    # plus what a script needs
#   scripts/bundle.sh --modules all -o dist/dybatpho.sh
#
#   # In the consuming project
#   . ./dybatpho.bundle.sh
#   dybatpho::info "ready, running dybatpho $(dybatpho::version)"
#
# @env DYBATPHO_FORCE string When true-like, overwrite an existing output file without asking
# @env DRY_RUN string When true-like, report what would be written and write nothing
#
# @see
#   - `init.sh`
#   - `src/doctor.sh`
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=init.sh
. "${SCRIPT_DIR}/../init.sh" --modules cli safety doctor

dybatpho::register_common_handlers

#######################################
# @description Ask the real bootstrap which modules a selection loads.
#   A child shell is used so the resolution is unaffected by what this script
#   already loaded, and it is written to a file because a `bash -c` shell has an
#   empty `BASH_SOURCE`, which `init.sh` refuses.
# @arg $1 string Module selection, as `--modules` accepts it
# @stdout The resolved module names, in load order, one per line
# @exitcode 1 Stop the script when the selection names an unknown module
#######################################
function __dybatpho_bundle_resolve {
  local _selection="$1"
  local _script
  dybatpho::create_temp _script ".sh" "bundle-resolve"
  {
    printf '. %q --modules %q\n' "${DYBATPHO_DIR}/init.sh" "${_selection}"
    printf 'dybatpho::module_list loaded\n'
  } > "${_script}"
  env -u DYBATPHO_MODULES -u DYBATPHO_LOADED_MODULES bash "${_script}" \
    || dybatpho::die "Can't resolve the module selection '${_selection}'"
}

#######################################
# @description Copy one function out of a source file, without its doc block.
#   The bundle needs the bootstrap's own functions, and copying them at
#   generation time keeps the generated file from drifting away from `init.sh`.
# @arg $1 path File to read
# @arg $2 string Function name
# @stdout The function definition, from its `function` line to its closing brace
# @exitcode 1 Stop the script when the function isn't found
#######################################
function __dybatpho_bundle_extract {
  local _file="$1" _name="$2" _body
  _body="$(awk -v name="${_name}" '
    $0 == "function " name " {" { collecting = 1 }
    collecting { print }
    collecting && $0 == "}" { exit }
  ' "${_file}")"
  [[ -n "${_body}" ]] \
    || dybatpho::die "Can't find function '${_name}' in ${_file}"
  printf '%s\n' "${_body}"
}

#######################################
# @description Write the bundle prologue: the guards, the environment, and the
#   bootstrap functions a sourced bundle still has to provide.
# @arg $1 string Space-separated module names, in load order
# @stdout The prologue
#######################################
function __dybatpho_bundle_prologue {
  local _modules="$1"
  local _core="${DYBATPHO_CORE_MODULES}"
  # Everything bundled that isn't core is optional, and the bundle knows about
  # no other module: a name outside this list cannot be loaded from a file that
  # does not carry it.
  local _optional="" _module
  for _module in ${_modules}; do
    [[ " ${_core} " == *" ${_module} "* ]] || _optional="${_optional:+${_optional} }${_module}"
  done

  cat << PROLOGUE
#!/usr/bin/env bash
# dybatpho $(dybatpho::version) bundle
# Modules: ${_modules}
#
# Generated by scripts/bundle.sh from the dybatpho library. Do not edit: change
# the library and regenerate. Source this file the way you would source
# init.sh; it carries no dependency on a src/ directory.
#
#   . ./$(dybatpho::path_basename "${OUTPUT}")

__dybatpho_bundle_source="\${BASH_SOURCE[0]-}"

if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 3))); then
  echo "dybatpho requires bash v4.3 or greater"
  echo "Current Bash Version: \${BASH_VERSION}"
  exit 1
fi

if [[ -n "\${__dybatpho_bundle_source}" && "\${__dybatpho_bundle_source}" == "\${0}" ]]; then
  echo "dybatpho can't be executed directly. Please source dybatpho."
  exit 1
fi

set -euo pipefail
shopt -s nullglob globstar
shopt -s extglob

if [[ -z "\${__dybatpho_bundle_source}" ]]; then
  echo "dybatpho couldn't resolve its source path. Please source the bundle from a file-backed shell context."
  exit 1
fi
DYBATPHO_DIR="\$(cd -- "\$(dirname "\${__dybatpho_bundle_source}")" && pwd)"
unset __dybatpho_bundle_source
export DYBATPHO_DIR

# The bundle carries its version rather than resolving one: there is no VERSION
# file beside it, and the repository it is vendored into has a version of its
# own that has nothing to do with this library.
DYBATPHO_VERSION="\${DYBATPHO_VERSION:-$(dybatpho::version)}"
DYBATPHO_CORE_MODULES="${_core}"
DYBATPHO_OPTIONAL_MODULES="${_optional}"
DYBATPHO_LOADED_MODULES="${_modules}"
export DYBATPHO_CORE_MODULES DYBATPHO_OPTIONAL_MODULES

$(__dybatpho_bundle_extract "${DYBATPHO_DIR}/init.sh" "__dybatpho_module_exists")

$(__dybatpho_bundle_extract "${DYBATPHO_DIR}/init.sh" "__dybatpho_export_functions")

$(__dybatpho_bundle_extract "${DYBATPHO_DIR}/init.sh" "dybatpho::version")

$(__dybatpho_bundle_extract "${DYBATPHO_DIR}/init.sh" "dybatpho::module_loaded")

$(__dybatpho_bundle_extract "${DYBATPHO_DIR}/init.sh" "dybatpho::module_list")

# A bundle has nothing to source: every module it carries is already loaded, and
# a module it doesn't carry can only come from regenerating it.
function dybatpho::load {
  (($#)) || dybatpho::die "dybatpho::load: Expected at least one module name"
  local module
  for module in "\$@"; do
    dybatpho::module_loaded "\${module}" && continue
    dybatpho::die "dybatpho::load: Module '\${module}' is not in this bundle. Regenerate it with: scripts/bundle.sh --modules \"${_modules} \${module}\""
  done
}
PROLOGUE
}

#######################################
# @description Write one module into the bundle, without its shebang.
# @arg $1 string Module name
# @stdout A section header and the module source
#######################################
function __dybatpho_bundle_module {
  local _module="$1"
  local _file="${DYBATPHO_DIR}/src/${_module}.sh"
  dybatpho::is file "${_file}" || dybatpho::die "No source file for module '${_module}'"
  printf '\n#--- module: %s %s\n' "${_module}" "$(dybatpho::string_repeat '-' 40)"
  # The shebang is dropped: only the first line of the bundle may carry one, and
  # the rest of the file is kept verbatim so that the bundled code and the
  # library code stay the same code.
  tail -n +2 "${_file}"
}

#######################################
# @description Generate the bundle and write it to the output path.
# @arg $1 string Ignored; positional arguments are rejected by the spec
# @stdout Progress, then the path of the written bundle
# @exitcode 1 Stop the script when overwriting the output is declined
#######################################
function __dybatpho_bundle_run {
  local _modules _module _count=0
  # shellcheck disable=SC2153 # MODULES is the option variable the CLI spec declares
  _modules="$(__dybatpho_bundle_resolve "${MODULES}" | tr '\n' ' ')"
  _modules="$(dybatpho::trim "${_modules}")"
  for _module in ${_modules}; do _count=$((_count + 1)); done
  dybatpho::progress "Bundling ${_count} module(s): ${_modules}"

  if dybatpho::is true "${DRY_RUN:-false}"; then
    dybatpho::info "DRY_RUN: would write ${_count} module(s) to ${OUTPUT}"
    return 0
  fi

  dybatpho::safe_overwrite "${OUTPUT}" || dybatpho::die "Aborted: ${OUTPUT} already exists"
  local _dir
  _dir="$(dybatpho::path_dirname "${OUTPUT}")"
  dybatpho::ensure_dir "${_dir}" > /dev/null

  {
    __dybatpho_bundle_prologue "${_modules}"
    for _module in ${_modules}; do
      __dybatpho_bundle_module "${_module}"
    done
    printf '\n__dybatpho_export_functions\n'
  } > "${OUTPUT}"
  chmod +r "${OUTPUT}"

  bash -n "${OUTPUT}" || dybatpho::die "The generated bundle is not valid Bash: ${OUTPUT}"
  __dybatpho_bundle_smoke "${OUTPUT}" "${_modules}"

  dybatpho::success "Wrote $(dybatpho::file_size "${OUTPUT}") bytes to ${OUTPUT}"
  printf '%s\n' "${OUTPUT}"
  return 0
}

#######################################
# @description Source the bundle in a pristine shell and check what it loaded.
#   A bundle that parses but cannot be sourced, or that reports a module set
#   other than the one asked for, is a broken artifact and must not be reported
#   as written.
# @arg $1 path The generated bundle
# @arg $2 string The module names it is expected to report, in load order
# @exitcode 1 Stop the script when sourcing the bundle fails or reports the wrong set
#######################################
# shellcheck disable=SC2016 # the printf literals below are generated shell source
function __dybatpho_bundle_smoke {
  local _bundle="$1" _expected="$2" _script _loaded
  dybatpho::create_temp _script ".sh" "bundle-smoke"
  {
    printf 'while read -r __fn; do unset -f "${__fn}"; done < <(compgen -A function "dybatpho::" || true)\n'
    printf '. %q\n' "${_bundle}"
    printf 'dybatpho::module_list loaded | tr "\\n" " "\n'
  } > "${_script}"
  _loaded="$(env -u DYBATPHO_DIR -u DYBATPHO_MODULES -u DYBATPHO_LOADED_MODULES \
    bash "${_script}")" || dybatpho::die "The generated bundle can't be sourced: ${_bundle}"
  _loaded="$(dybatpho::trim "${_loaded}")"
  [[ "${_loaded}" == "${_expected}" ]] \
    || dybatpho::die "The bundle reports '${_loaded}' instead of '${_expected}'"
}

function _spec {
  dybatpho::opts::setup "Flatten dybatpho modules into one self-contained file" \
    BUNDLE_ARGS action:"__dybatpho_bundle_run" args:none

  dybatpho::opts::param "Modules to bundle, as init.sh accepts them" MODULES \
    -m --modules env:DYBATPHO_MODULES init:="core"
  dybatpho::opts::param "Path of the generated bundle" OUTPUT \
    -o --output init:="${PWD}/dybatpho.bundle.sh"

  dybatpho::opts::disp "Show help" --help action:"dybatpho::generate_help _spec"
}

dybatpho::generate_from_spec _spec "$@"
